#pragma once

#define VER_PRODUCTBUILD 560
#define VER_PRODUCTVERSION_STR_W L"[Custom Build] v1.6.0560.0 (TU19)"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"REPO: chrisGrando/MinecraftLCE-7thGen/main"
#define VER_NETWORK VER_PRODUCTBUILD
